MOB-3432 Add "login with karhoo credentials" (token) to Network SDK
karhoo/karhoo-android-sdk pull request #117
Opened 2021-07-12 14:01 UTC by mateid-kr

## JIRA
[MOB-3432](https://karhoo.atlassian.net/browse/MOB-3432)

## DESCRIPTION
 Add "login with KH credentials" to Network SDK

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [X] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [X] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [X] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2021-07-13 08:21 UTC, EdwardW2 requested changes
Best to fix the wildcard import

2021-07-13 08:21 UTC, EdwardW2 commented on sdk/src/test/java/com/karhoo/sdk/api/service/auth/AuthLoginWithCredentialsInteractorTest.kt
> +import com.nhaarman.mockitokotlin2.*
Fix wildcard import

2021-07-14 13:34 UTC, mohadian approved these changes

2021-07-14 13:49 UTC, EdwardW2 approved these changes

2021-07-14 13:49 UTC, merged