Mob-3640 add loyalty program APIs
karhoo/karhoo-android-sdk pull request #131
Opened 2021-11-23 08:56 UTC by mionescu95

## JIRA
[MOB-3640](https://karhoo.atlassian.net/browse/MOB-3640)

## DESCRIPTION
Added Loyalty APIs

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [x] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2021-11-24 13:57 UTC, mateid-kr requested changes

2021-11-24 13:57 UTC, mateid-kr commented on sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/LoyaltyBurnPointsInteractor.kt
> +    BaseCallInteractor<LoyaltyPoints>(true, credentialsManager, apiTemplate, context) {
Boolean literal argument is without parameter name. Maybe add the param name also:
requestRequiresToken = true

2021-11-24 13:57 UTC, mateid-kr commented on sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/LoyaltyBurnPointsInteractor.kt
> +    internal var loyaltyId: String? = null
the properties can be made private, don't think there's a reason to be made internal.

2021-11-24 13:57 UTC, mateid-kr commented on sdk/src/main/java/com/karhoo/sdk/api/network/client/APITemplate.kt
> +    String, @Query(IDENTIFIER_TOTALAMOUNT) totalAmount: Int, @Query(IDENTIFIER_BURNPOINTS)
The identation seems broken here, we should have params on separate lines for easier reading. Same applies to above

2021-11-24 13:57 UTC, mateid-kr commented on sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/LoyaltyBurnPointsInteractor.kt
> +    internal var loyaltyId: String? = null
They can be passed in from the constructor

2021-11-24 13:57 UTC, mateid-kr commented on sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/LoyaltyPointsToEarnInteractor.kt
> +internal class LoyaltyPointsToEarnInteractor @Inject constructor(credentialsManager: CredentialsManager,
I have mixed feelings about having two separate interactors, we could have one which handles both earning and burning scenarios 
@mohadian what do you think?

2021-11-24 13:57 UTC, mateid-kr commented on sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/LoyaltyBurnPointsInteractor.kt
> +    internal var loyaltyId: String? = null
Same applies for the below properties in the LoyaltyPointsToEarnInteractor

2021-11-24 13:58 UTC, mateid-kr commented on sdk/src/main/java/com/karhoo/sdk/api/service/loyalty/LoyaltyStatusInteractor.kt
> +internal class LoyaltyStatusInteractor @Inject constructor(credentialsManager: CredentialsManager,
There are no unit tests for these interactors / requests

2021-11-26 09:12 UTC, mohadian commented on sdk/src/main/java/com/karhoo/sdk/api/network/request/LoyaltyPreAuth.kt
> +data class LoyaltyPreAuth(@SerializedName("currency") val currency: String? = null,
the ios LoyaltyPreAuth contains 
`public let identifier: String`

I think the identifier can be removed in the iOS version (Android is fine?)

2021-11-26 09:13 UTC, mohadian commented on sdk/src/main/java/com/karhoo/sdk/api/network/request/LoyaltyPreAuth.kt
> +                       @SerializedName("loyalty_membership") val loyaltyMembership: String? = null) : Parcelable
in the iOS, it is called `membership: String`

2021-11-29 17:05 UTC, mateid-kr approved these changes

2021-11-30 06:24 UTC, merged